// Mock data for UI development. Timestamps are ISO strings; numerics are JS numbers.
// Real DB queries return Date objects and string numerics (Drizzle types).

import type { SpyTracker, OptimizerRule, ActionLog } from '@/lib/db'

export const MOCK_SPY_TRACKERS = ([
  {
    id: 'tr_1',
    agency_id: 'agency_1',
    created_by: 'user_1',
    name: 'Nike US Footwear',
    competitor_name: 'Nike',
    competitor_page_url: 'https://www.facebook.com/nike',
    competitor_page_id: '1234567890',
    country_code: 'US',
    search_terms: ['running shoes', 'air max'],
    ad_types: ['IMAGE', 'VIDEO', 'CAROUSEL'],
    min_longevity_days: 14,
    max_results: 50,
    schedule_cron: '0 6 * * *',
    status: 'active',
    meta_ad_account_id: 'account_1',
    last_run_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    apify_run_id: 'run_abc123',
    last_report_summary: {
      top_ads_count: 8,
      avg_longevity_days: 32,
      top_format: 'VIDEO',
      insights: 'Nike is scaling video ads featuring user-generated content. 3 carousel ads have been running 45+ days.',
    },
    total_runs: 12,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tr_2',
    agency_id: 'agency_1',
    created_by: 'user_1',
    name: 'Apple AirPods Campaign',
    competitor_name: 'Apple',
    competitor_page_url: 'https://www.facebook.com/apple',
    competitor_page_id: '9876543210',
    country_code: 'GB',
    search_terms: ['airpods', 'wireless earbuds'],
    ad_types: ['VIDEO', 'IMAGE'],
    min_longevity_days: 7,
    max_results: 30,
    schedule_cron: '0 8 * * *',
    status: 'active',
    meta_ad_account_id: 'account_1',
    last_run_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
    apify_run_id: 'run_def456',
    last_report_summary: {
      top_ads_count: 5,
      avg_longevity_days: 21,
      top_format: 'VIDEO',
      insights: 'Apple is running a consistent 15-second video format. High spend on UK demographic 25-44.',
    },
    total_runs: 7,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tr_3',
    agency_id: 'agency_1',
    created_by: 'user_1',
    name: 'Gymshark EU',
    competitor_name: 'Gymshark',
    competitor_page_url: 'https://www.facebook.com/gymshark',
    competitor_page_id: '1122334455',
    country_code: 'DE',
    search_terms: ['gym wear', 'activewear'],
    ad_types: ['IMAGE', 'CAROUSEL'],
    min_longevity_days: 10,
    max_results: 40,
    schedule_cron: '0 7 * * 1',
    status: 'paused',
    meta_ad_account_id: null,
    last_run_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    next_run_at: null,
    apify_run_id: null,
    last_report_summary: null,
    total_runs: 3,
    created_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
]) as unknown as SpyTracker[]

export const MOCK_OPTIMIZER_RULES = ([
  {
    id: 'rule_1',
    agency_id: 'agency_1',
    created_by: 'user_1',
    meta_ad_account_id: 'account_1',
    campaign_name: 'ASC – Spring Collection 2026',
    account_name: 'Acme Brand – US',
    name: 'Spring Collection Safety Rails',
    description: 'Conservative guardrails for the high-spend spring launch',
    scope: 'account',
    campaign_ids: ['23851234567890'],
    adset_ids: [],
    max_daily_budget_usd: 2500,
    min_daily_budget_usd: 500,
    max_budget_increase_pct: 20,
    max_budget_decrease_pct: 30,
    target_roas: 3.5,
    min_roas_threshold: 1.8,
    attribution_window: '7d_click',
    min_spend_before_action_usd: 75,
    max_ad_frequency: 4.5,
    max_cpm_increase_pct: 25,
    max_bid_cap_usd: null,
    check_interval_minutes: 60,
    schedule_cron: '0 * * * *',
    require_approval: true,
    auto_approve_below_usd: 0,
    status: 'active',
    last_run_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 5 * 60 * 1000).toISOString(),
    total_actions_taken: 14,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
  },
  {
    id: 'rule_2',
    agency_id: 'agency_1',
    created_by: 'user_1',
    meta_ad_account_id: 'account_2',
    campaign_name: 'Retargeting – Abandoned Cart',
    account_name: 'Acme Brand – EU',
    name: 'Retargeting Efficiency Rules',
    description: 'Aggressive ROAS targeting for warm retargeting audience',
    scope: 'campaign',
    campaign_ids: ['23851234567891'],
    adset_ids: [],
    max_daily_budget_usd: 800,
    min_daily_budget_usd: 100,
    max_budget_increase_pct: 15,
    max_budget_decrease_pct: 40,
    target_roas: 5.0,
    min_roas_threshold: 2.5,
    attribution_window: '1d_click',
    min_spend_before_action_usd: 50,
    max_ad_frequency: 6.0,
    max_cpm_increase_pct: null,
    max_bid_cap_usd: 8.00,
    check_interval_minutes: 30,
    schedule_cron: '*/30 * * * *',
    require_approval: true,
    auto_approve_below_usd: 50,
    status: 'active',
    last_run_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 2 * 60 * 1000).toISOString(),
    total_actions_taken: 31,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
]) as unknown as (OptimizerRule & { campaign_name: string; account_name: string })[]

export const MOCK_ACTION_LOGS = ([
  {
    id: 'log_1',
    agency_id: 'agency_1',
    agent_type: 'optimizer',
    action_type: 'INCREASE_BUDGET',
    meta_ad_account_id: 'account_1',
    optimizer_rule_id: 'rule_1',
    spy_tracker_id: null,
    target_entity_type: 'campaign',
    target_entity_id: '23851234567890',
    target_entity_name: 'ASC – Spring Collection 2026',
    current_value: { daily_budget_usd: 1200 },
    proposed_value: { daily_budget_usd: 1440 },
    reasoning: 'Campaign ROAS has averaged 4.2x over the last 7-day window (target: 3.5x). Spend is $820 below the $2,500 daily ceiling. A 20% budget increase is projected to capture an additional 340 high-intent users based on current CPM trends.',
    confidence_score: 0.87,
    status: 'pending_human_approval',
    requires_approval: true,
    approved_by: null,
    approved_at: null,
    denied_by: null,
    denied_at: null,
    denial_reason: null,
    executing_at: null,
    executed_at: null,
    execution_result: null,
    error_message: null,
    langgraph_thread_id: 'thread_optimizer_001',
    langgraph_checkpoint: { step: 'wait_for_human', iteration: 3 },
    created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 23.7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log_2',
    agency_id: 'agency_1',
    agent_type: 'optimizer',
    action_type: 'PAUSE_AD',
    meta_ad_account_id: 'account_1',
    optimizer_rule_id: 'rule_1',
    spy_tracker_id: null,
    target_entity_type: 'ad',
    target_entity_id: 'ad_987654321',
    target_entity_name: 'Spring Hoodie – Static Image v3',
    current_value: { status: 'ACTIVE', spend_7d: 312.40, roas_7d: 1.3 },
    proposed_value: { status: 'PAUSED' },
    reasoning: 'This ad has spent $312 over the 7-day attribution window with a ROAS of 1.3x — below the 1.8x minimum threshold. The ad has exceeded the $75 minimum spend gate. Pausing will reallocate budget to the 3 higher-performing creatives in this campaign.',
    confidence_score: 0.94,
    status: 'pending_human_approval',
    requires_approval: true,
    approved_by: null,
    approved_at: null,
    denied_by: null,
    denied_at: null,
    denial_reason: null,
    executing_at: null,
    executed_at: null,
    execution_result: null,
    error_message: null,
    langgraph_thread_id: 'thread_optimizer_002',
    langgraph_checkpoint: { step: 'wait_for_human', iteration: 1 },
    created_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 23.3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log_3',
    agency_id: 'agency_1',
    agent_type: 'spy',
    action_type: 'SPY_REPORT_READY',
    meta_ad_account_id: null,
    optimizer_rule_id: null,
    spy_tracker_id: 'tr_1',
    target_entity_type: 'report',
    target_entity_id: 'run_abc123',
    target_entity_name: 'Nike US Footwear – Daily Report',
    current_value: null,
    proposed_value: {
      top_ads: 8,
      longest_running_days: 61,
      dominant_format: 'VIDEO',
      key_insight: 'Nike is heavily scaling 6-second bumper video ads. Their top performer has been live 61 days.',
    },
    reasoning: 'Daily Apify scan completed. Found 8 ads running 14+ days. Top creative: 61-day video featuring celebrity athlete with UGC-style editing. Recommend testing similar format.',
    confidence_score: 1.0,
    status: 'pending_human_approval',
    requires_approval: false,
    approved_by: null,
    approved_at: null,
    denied_by: null,
    denied_at: null,
    denial_reason: null,
    executing_at: null,
    executed_at: null,
    execution_result: null,
    error_message: null,
    langgraph_thread_id: 'thread_spy_001',
    langgraph_checkpoint: null,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'log_4',
    agency_id: 'agency_1',
    agent_type: 'optimizer',
    action_type: 'INCREASE_BUDGET',
    meta_ad_account_id: 'account_2',
    optimizer_rule_id: 'rule_2',
    spy_tracker_id: null,
    target_entity_type: 'adset',
    target_entity_id: 'adset_111222333',
    target_entity_name: 'Retargeting – All Visitors 30d',
    current_value: { daily_budget_usd: 200 },
    proposed_value: { daily_budget_usd: 230 },
    reasoning: '1-day click ROAS is 6.1x against a 5.0x target. Frequency is 3.2 (below 6.0 cap). $30 increase stays within the $800 account ceiling. Auto-approval threshold is $50; this delta is $30.',
    confidence_score: 0.91,
    status: 'auto_approved',
    requires_approval: false,
    approved_by: null,
    approved_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    denied_by: null,
    denied_at: null,
    denial_reason: null,
    executing_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    executed_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    execution_result: { success: true, meta_response: { id: 'adset_111222333' } },
    error_message: null,
    langgraph_thread_id: 'thread_optimizer_003',
    langgraph_checkpoint: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
  },
]) as unknown as ActionLog[]

export const MOCK_DASHBOARD_STATS = {
  activeAgents: 2,
  pendingApprovals: MOCK_ACTION_LOGS.filter(l => l.status === 'pending_human_approval').length,
  totalSpendOptimized: 284521,
  roasImprovement: 23,
  actionsTakenThisWeek: 31,
  hoursSaved: 14,
}
